.TH XLENCY "1" "August 2020" "xlency 1.0" "User Commands"
.SH NAME
xlency \- manual page for xlency 1.0
.SH DESCRIPTION
The Excel file decoder.
.SS "USAGE:"
.IP
xlency [Vh] [fose]
.SS "OPTIONS:"
.TP
\fB\-V\fR, \fB\-\-version\fR
Print the version of the software ane exit
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this message and exit
.TP
\fB\-f\fR, \fB\-\-file\fR
Input Excel file
.TP
\fB\-o\fR, \fB\-\-outfile\fR
Output `csv` file
.TP
\fB\-s\fR, \fB\-\-start\fR
Start coordinate for the Excel file
.TP
\fB\-e\fR, \fB\-\-end\fR
End coordinate for the Excel file
.TP
\fB\-S\fR, \fB\-\-sheet\fR
Worksheet name for the Excel file
.SH COPYRIGHT
Copyright \(co 2020 Barthandelous01
License RBSD 3\-Clause License.
.br
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
